name: CI Pipeline
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    concurrency: ci-${{github.ref}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.head_ref}}

      - name: Pull LFS Models
        run: git lfs pull

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
            node-version: ${{matrix.node-version}}
            cache: "yarn"
            cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          cd dist
          git init
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add -A
          git commit -m "build: ${{github.sha}}"
          git push -f https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master:gh-pages
